### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named 'transition'

### ISSUE THREAD

**Issue by surjithctly** [sacarvy/petiteVueTransition#4]
I'm using the direct cdn method. 

```
import { transition } from "https://unpkg.com/vue-petite-transition@2.0.0/dist/vue-petite-transition.es.js";
```

But when I add it's throwing the following error:

```
Uncaught SyntaxError: The requested module does not provide an export named 'transition'
```

See minimal reproduction on codepen: https://codepen.io/surjithctly/pen/qBKMYWr

Can you provide any guidance?

**Comment by goalphadev** [comment]
okay, let me check this.

**Comment by q1b** [comment]
Thanks, for reporting it. 

I haven't tested It before, let me check.

**Comment by q1b** [comment]
It should work although, but not working must I am doing something wrong.

**Comment by q1b** [comment]
Okay, find the issue.

```html
<script type="module">
  import { createApp } from 'https://unpkg.com/petite-vue?module'
  import { transitionDirective } from "https://unpkg.com/vue-petite-transition@2.0.0/dist/vue-petite-transition.es.js";
  createApp().directive("transition", transitionDirective).mount()
</script>
```

this is working.

**Comment by q1b** [comment]
It's a quick fix

**Comment by q1b** [comment]
I need to document it, If everything is working for you, you can close the issue.
Or ask any other question.

**Comment by surjithctly** [comment]
yes, it's working, Thank you. The documentation seems wrong.

**Comment by surjithctly** [comment]
Added a PR that closes this issue. You can merge it if it looks good :)
